#!/bin/bash
#
# LICENSE: CC0
#

n=128
n2=`echo "$n / 2" | bc `

../../../bin/poms.ir \
  -s $n,$n,1 \
  -P $n2,$n2,0 \
  -C ../data/oarpgo_poms_wUbW3x3.json > oarpgo_simple_wUbW3x3.taccl

../../../bin/poms.ir \
  -F 1 \
  -s $n,$n,1 \
  -P $n2,$n2,0 \
  -C ../data/oarpgo_poms_wUbW3x3.json > oarpgo_freq_wUbW3x3.taccl
 
