#!/bin/bash

# NOTE: yajl needs some magic invocation of
#       emconfigure or emcmake to build the libyajl.a
#       file or else it'll search for some `yajl_tree.c.o` or
#       or some such.
#       Also, manually symlink libyajl_s.a to libyajl.a
#
# * go into yajl:                       emconfigure ./configure
# * go into yajl/build:                 emmake make
# * go into yajl/build/yajl-2.1.1/lib:  ln -s libyajl_s.a libyajl.a
#

em++ \
  -DCUSTOM_MAIN \
  -O2 \
  -s LLD_REPORT_UNDEFINED \
  -I ./yajl-2.1.1/include \
  ./yajl-2.1.1/lib/libyajl.a \
  ./tiny_obj_loader.c \
  ./main_poms.cpp \
  ./auxExport.cpp \
  ./pomsAlgorithm.cpp \
  ./pomsConstraintPropagate.cpp \
  ./pomsDebug.cpp \
  ./pomsEntropy.cpp \
  ./pomsExport.cpp \
  ./pomsLoad.cpp \
  ./pomsRegionQuilting.cpp \
  ./TiledExport.cpp \
  ./web_poms.cpp \
  --preload-file 'html/data/pillMortal_poms.json@data/' \
  --preload-file 'html/data/forestmicro_poms.json@data/' \
  --preload-file 'html/data/neondungeon_poms.json@data/' \
  --preload-file 'html/data/neonsnow_poms.json@data/' \
  --preload-file 'html/data/neondirt_poms.json@data/' \
  --preload-file 'html/data/2bmmv_poms.json@data/' \
  --preload-file 'html/data/1985_poms.json@data/' \
  --preload-file 'html/data/minirogue_poms.json@data/' \
  --preload-file 'html/data/amarelo_poms.json@data/' \
  --preload-file 'html/data/kyst_poms.json@data/' \
  --preload-file 'html/data/mccaves_poms.json@data/' \
  --preload-file 'html/data/island_poms.json@data/' \
  --preload-file 'html/data/blowharder_poms.json@data/' \
  --preload-file 'html/data/psygen_poms.json@data/' \
  --preload-file 'html/data/vilenes_poms.json@data/' \
  --preload-file 'html/data/oarpgo_poms.json@data/' \
  -sEXPORTED_RUNTIME_METHODS=ccall,cwrap,setValue \
  -sALLOW_MEMORY_GROWTH=1 \
  -sMAXIMUM_MEMORY=4294967296 \
  -o html/js/poms.js

#  -s EXPORTED_FUNCTIONS="['_custom_function', '_main']" \

