#!/bin/bash
#
# LICENSE: CC0
#

n=256
n2=`echo "$n / 2" | bc `

../../../bin/poms.ir \
  -s $n,$n,1 \
  -P $n2,$n2,0 \
  -C ../data/vilenes_poms.json > vilenes_simple.accl

../../../bin/poms.ir \
  -F 1 \
  -s $n,$n,1 \
  -P $n2,$n2,0 \
  -C ../data/vilenes_poms.json > vilenes_freq.accl

  
 
