#!/bin/bash
#
# LICENSE: CC0
#


tfn=`mktemp`
./create-rule-graph  > $tfn.dot
dot -Kfdp -n -Tsvg -o $tfn.svg $tfn.dot
inkscape -d 300 -o $tfn.eps $tfn.svg
./post-process-svg $tfn.svg > $tfn.svg1
cp $tfn.svg1 pm_rule_grid.svg
inkscape -d 300 -w 4096 -h 4096 pm_rule_grid.svg -o pm_rule_grid.png

rm -f $tfn $tfn.dot $tfn.svg $tfn.eps $tfn.svg1

echo "pm_rule_grid.svg"
echo "pm_rule_grid.png"

