#!/bin/bash
#
# LICENSE: CC0
#

n=64
n2=`echo "$n / 2" | bc `

../../../bin/poms.ir \
  -s $n,$n,1 \
  -P $n2,$n2,0 \
  -C ../data/blowharder_poms.json > blowharder_simple.taccl

../../../bin/poms.ir \
  -F 1 \
  -s $n,$n,1 \
  -P $n2,$n2,0 \
  -C ../data/blowharder_poms.json > blowharder_freq.taccl
 
