#!/usr/bin/python3
#
# To the extent possible under law, the person who associated CC0 with
# this work has waived all copyright and related or neighboring rights
# to this work.
#
# You should have received a copy of the CC0 legalcode along with this
# work. If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
#

import sys
import re
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as colors

TILESET_NAME = "2BMMV"

def loadfile(fn):
  a = []
  with open(fn) as fp:
    for line in fp:
      line = line.strip()
      if len(line)==0: continue
      if line[0] == '#': continue

      tok = re.split('  *', line);

      v = []
      for t in tok:
        v.append( int(t) )
      a.append(v)

  nd_a = np.array(a)
  return nd_a

simple_taccl = loadfile("2bmmv_simple.taccl")
freq_taccl = loadfile("2bmmv_freq.taccl")


def outplot(nd_a, fn, title):
  im = plt.imshow(nd_a, cmap='viridis', interpolation='nearest', norm=colors.SymLogNorm(linthresh=1, vmin=nd_a.min(), vmax=nd_a.max(), base=10))

  plt.rcParams.update({'font.size':20})

  plt.xlabel("x", fontsize=24)
  plt.ylabel("y", fontsize=24)
  plt.title(title, fontdict = {'fontsize':24})

  plt.colorbar(im)

  plt.savefig(fn, bbox_inches='tight', dpi=300)
  plt.clf()


outplot(simple_taccl, "2bmmv_simple_taccl.png", TILESET_NAME + "\nSimple TACCL")
outplot(freq_taccl, "2bmmv_freq_taccl.png", TILESET_NAME + "\nFrequency TACCL")

outplot(simple_taccl, "2bmmv_simple_taccl.svg", TILESET_NAME + "\nSimple TACCL")
outplot(freq_taccl, "2bmmv_freq_taccl.svg", TILESET_NAME + "\nFrequency TACCL")

#outplot(simple_taccl, "2bmmv_simple_taccl.png", TILESET_NAME + "\nSimple Tile Arc Consistent Correlation Length")
#outplot(freq_taccl, "2bmmv_freq_taccl.png", TILESET_NAME + "\nFrequency Tile Arc Consistent Correlation Length")



